/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PreguntasRouteImport } from './routes/preguntas'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SolicitarRouteImport } from './routes/solicitar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasRoute = PreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/preguntas': typeof PreguntasRoute
  '/privacidad': typeof PrivacidadRoute
  '/solicitar': typeof SolicitarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/preguntas': typeof PreguntasRoute
  '/privacidad': typeof PrivacidadRoute
  '/solicitar': typeof SolicitarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cobertura': typeof CoberturaRoute
  '/contacto': typeof ContactoRoute
  '/planes': typeof PlanesRoute
  '/preguntas': typeof PreguntasRoute
  '/privacidad': typeof PrivacidadRoute
  '/solicitar': typeof SolicitarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cobertura'
    | '/contacto'
    | '/planes'
    | '/preguntas'
    | '/privacidad'
    | '/solicitar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cobertura'
    | '/contacto'
    | '/planes'
    | '/preguntas'
    | '/privacidad'
    | '/solicitar'
  id:
    | '__root__'
    | '/'
    | '/cobertura'
    | '/contacto'
    | '/planes'
    | '/preguntas'
    | '/privacidad'
    | '/solicitar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoberturaRoute: typeof CoberturaRoute
  ContactoRoute: typeof ContactoRoute
  PlanesRoute: typeof PlanesRoute
  PreguntasRoute: typeof PreguntasRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SolicitarRoute: typeof SolicitarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas': {
      id: '/preguntas'
      path: '/preguntas'
      fullPath: '/preguntas'
      preLoaderRoute: typeof PreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoberturaRoute: CoberturaRoute,
  ContactoRoute: ContactoRoute,
  PlanesRoute: PlanesRoute,
  PreguntasRoute: PreguntasRoute,
  PrivacidadRoute: PrivacidadRoute,
  SolicitarRoute: SolicitarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
